//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_104884 {
            get {
                object obj = ResourceManager.GetObject("11_104884", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_1048841 {
            get {
                object obj = ResourceManager.GetObject("11_1048841", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1157ece472d4082becb8c9946f9399d7 {
            get {
                object obj = ResourceManager.GetObject("1157ece472d4082becb8c9946f9399d7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486485588_add_create_new_math_sign_cross_plus_81186 {
            get {
                object obj = ResourceManager.GetObject("1486485588-add-create-new-math-sign-cross-plus_81186", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486485588_add_create_new_math_sign_cross_plus_811861 {
            get {
                object obj = ResourceManager.GetObject("1486485588-add-create-new-math-sign-cross-plus_811861", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486485588_add_create_new_math_sign_cross_plus_811862 {
            get {
                object obj = ResourceManager.GetObject("1486485588-add-create-new-math-sign-cross-plus_811862", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486485589_about_error_notification_help_info_information_81162 {
            get {
                object obj = ResourceManager.GetObject("1486485589-about-error-notification-help-info-information_81162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1486504328_bullet_list_menu_lines_points_items_options_81334 {
            get {
                object obj = ResourceManager.GetObject("1486504328-bullet-list-menu-lines-points-items-options_81334", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _188514339_145859157600024_379318113328265145_n {
            get {
                object obj = ResourceManager.GetObject("188514339_145859157600024_379318113328265145_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2799201_jigsaw_processing_99781 {
            get {
                object obj = ResourceManager.GetObject("2799201-jigsaw-processing_99781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2799201_jigsaw_processing_997811 {
            get {
                object obj = ResourceManager.GetObject("2799201-jigsaw-processing_997811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2799204_management_99783 {
            get {
                object obj = ResourceManager.GetObject("2799204-management_99783", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2799204_management_997831 {
            get {
                object obj = ResourceManager.GetObject("2799204-management_997831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2799208_bag_business_99786 {
            get {
                object obj = ResourceManager.GetObject("2799208-bag-business_99786", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3289557_clan_group_partners_peers_people_107100 {
            get {
                object obj = ResourceManager.GetObject("3289557-clan-group-partners-peers-people_107100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3289557_clan_group_partners_peers_people_1071001 {
            get {
                object obj = ResourceManager.GetObject("3289557-clan-group-partners-peers-people_1071001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3289557_clan_group_partners_peers_people_1071002 {
            get {
                object obj = ResourceManager.GetObject("3289557-clan-group-partners-peers-people_1071002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32officeicons_3_89720 {
            get {
                object obj = ResourceManager.GetObject("32officeicons-3_89720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3440901_box_carton_delivery_ecommerce_package_return_shipping_107530 {
            get {
                object obj = ResourceManager.GetObject("3440901-box-carton-delivery-ecommerce-package-return-shipping_107530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3592827_access_general_house_key_key_lock_key_login_office_107758 {
            get {
                object obj = ResourceManager.GetObject("3592827-access-general-house-key-key-lock-key-login-office_107758", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3643745_human_man_people_person_profile_113435 {
            get {
                object obj = ResourceManager.GetObject("3643745-human-man-people-person-profile_113435", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3643762_find_glass_magnifying_search_zoom_113420 {
            get {
                object obj = ResourceManager.GetObject("3643762-find-glass-magnifying-search-zoom_113420", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4544831_business_comerce_delivery_return_shop_121431 {
            get {
                object obj = ResourceManager.GetObject("4544831-business-comerce-delivery-return-shop_121431", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba6 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba61 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba610 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba610", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba62 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba63 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba64 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba65 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba66 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba67 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba68 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c01afda97f678cf801271eebb041ba69 {
            get {
                object obj = ResourceManager.GetObject("5c01afda97f678cf801271eebb041ba69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _weather_lightning_98198 {
            get {
                object obj = ResourceManager.GetObject("-weather-lightning_98198", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _weather_lightning_981981 {
            get {
                object obj = ResourceManager.GetObject("-weather-lightning_981981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _weather_lightning_981982 {
            get {
                object obj = ResourceManager.GetObject("-weather-lightning_981982", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _weather_lightning_981983 {
            get {
                object obj = ResourceManager.GetObject("-weather-lightning_981983", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytics_118088 {
            get {
                object obj = ResourceManager.GetObject("analytics_118088", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytics_1180881 {
            get {
                object obj = ResourceManager.GetObject("analytics_1180881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytics_1180882 {
            get {
                object obj = ResourceManager.GetObject("analytics_1180882", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bars_chart_ascending_icon_icons_com_56865 {
            get {
                object obj = ResourceManager.GetObject("bars-chart-ascending_icon-icons.com_56865", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beautiful_color_ui_gradients_backgrounds_endless_river {
            get {
                object obj = ResourceManager.GetObject("beautiful-color-ui-gradients-backgrounds-endless-river", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beautiful_color_ui_gradients_backgrounds_endless_river1 {
            get {
                object obj = ResourceManager.GetObject("beautiful-color-ui-gradients-backgrounds-endless-river1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beautiful_color_ui_gradients_backgrounds_socialive {
            get {
                object obj = ResourceManager.GetObject("beautiful-color-ui-gradients-backgrounds-socialive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beautiful_color_ui_gradients_backgrounds_socialive1 {
            get {
                object obj = ResourceManager.GetObject("beautiful-color-ui-gradients-backgrounds-socialive1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booking_hotel_icon_141823 {
            get {
                object obj = ResourceManager.GetObject("booking_hotel_icon_141823", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booking_hotel_icon_1418231 {
            get {
                object obj = ResourceManager.GetObject("booking_hotel_icon_1418231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booking_hotel_icon_1418232 {
            get {
                object obj = ResourceManager.GetObject("booking_hotel_icon_1418232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booking_hotel_icon_1418233 {
            get {
                object obj = ResourceManager.GetObject("booking_hotel_icon_1418233", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booking_hotel_icon_1418234 {
            get {
                object obj = ResourceManager.GetObject("booking_hotel_icon_1418234", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booking_hotel_icon_1418235 {
            get {
                object obj = ResourceManager.GetObject("booking_hotel_icon_1418235", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_color_money_coins_icon_icons_com_53446 {
            get {
                object obj = ResourceManager.GetObject("business-color_money-coins_icon-icons.com_53446", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_color_money_coins_icon_icons1 {
            get {
                object obj = ResourceManager.GetObject("business-color_money-coins_icon-icons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_form_116472 {
            get {
                object obj = ResourceManager.GetObject("check-form_116472", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closeout_cierre_259 {
            get {
                object obj = ResourceManager.GetObject("Closeout_cierre_259", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closeout_cierre_2591 {
            get {
                object obj = ResourceManager.GetObject("Closeout_cierre_2591", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_add_114467 {
            get {
                object obj = ResourceManager.GetObject("document-add_114467", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_add_1144671 {
            get {
                object obj = ResourceManager.GetObject("document-add_1144671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_add_1144672 {
            get {
                object obj = ResourceManager.GetObject("document-add_1144672", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engine_gear_internet_option_security_setting_web_icon_127066 {
            get {
                object obj = ResourceManager.GetObject("engine_gear_internet_option_security_setting_web_icon_127066", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_delete_114438 {
            get {
                object obj = ResourceManager.GetObject("file-delete_114438", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_delete_1144381 {
            get {
                object obj = ResourceManager.GetObject("file-delete_1144381", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap findtheuser_search_search_theuser_4518 {
            get {
                object obj = ResourceManager.GetObject("findtheuser_search_search_theuser_4518", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap findtheuser_search_search_theuser_45181 {
            get {
                object obj = ResourceManager.GetObject("findtheuser_search_search_theuser_45181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap findtheuser_search_search_theuser_45182 {
            get {
                object obj = ResourceManager.GetObject("findtheuser_search_search_theuser_45182", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fitness_center_icon_150152 {
            get {
                object obj = ResourceManager.GetObject("fitness_center_icon_150152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fitness_center_icon_1501521 {
            get {
                object obj = ResourceManager.GetObject("fitness_center_icon_1501521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_style_circle_save_icon_icons_com_66942 {
            get {
                object obj = ResourceManager.GetObject("flat-style-circle-save_icon-icons.com_66942", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_style_circle_save_icon_icons1 {
            get {
                object obj = ResourceManager.GetObject("flat-style-circle-save_icon-icons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_style_circle_save_icon_icons2 {
            get {
                object obj = ResourceManager.GetObject("flat-style-circle-save_icon-icons2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient_black_green_linear_1920x1080_c2_000000_008080_a_90_f_14 {
            get {
                object obj = ResourceManager.GetObject("gradient-black-green-linear-1920x1080-c2-000000-008080-a-90-f-14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient_blue_1556830182x42 {
            get {
                object obj = ResourceManager.GetObject("gradient-blue-1556830182x42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient_blue_1556830182x421 {
            get {
                object obj = ResourceManager.GetObject("gradient-blue-1556830182x421", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient_blue_1556830182x422 {
            get {
                object obj = ResourceManager.GetObject("gradient-blue-1556830182x422", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphmagnifier_118081 {
            get {
                object obj = ResourceManager.GetObject("graphmagnifier_118081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpIndex_locate_find_6213 {
            get {
                object obj = ResourceManager.GetObject("HelpIndex_locate_find_6213", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpIndex_locate_find_62131 {
            get {
                object obj = ResourceManager.GetObject("HelpIndex_locate_find_62131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlighter_green_15056 {
            get {
                object obj = ResourceManager.GetObject("highlighter_green_15056", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlighter_green_150561 {
            get {
                object obj = ResourceManager.GetObject("highlighter_green_150561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_house_icon_icons_com_49851 {
            get {
                object obj = ResourceManager.GetObject("home_house_icon-icons.com_49851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_set_of_house_clipart_icon_187233 {
            get {
                object obj = ResourceManager.GetObject("home_set_of_house_clipart_icon_187233", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_set_of_house_clipart_icon_1872331 {
            get {
                object obj = ResourceManager.GetObject("home_set_of_house_clipart_icon_1872331", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_43674 {
            get {
                object obj = ResourceManager.GetObject("Hotel_43674", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_436741 {
            get {
                object obj = ResourceManager.GetObject("Hotel_436741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_436742 {
            get {
                object obj = ResourceManager.GetObject("Hotel_436742", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_436743 {
            get {
                object obj = ResourceManager.GetObject("Hotel_436743", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_Check_In_43673 {
            get {
                object obj = ResourceManager.GetObject("Hotel-Check-In_43673", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_Check_In_436731 {
            get {
                object obj = ResourceManager.GetObject("Hotel-Check-In_436731", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_Check_In_436732 {
            get {
                object obj = ResourceManager.GetObject("Hotel-Check-In_436732", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hotel_Check_In_436733 {
            get {
                object obj = ResourceManager.GetObject("Hotel-Check-In_436733", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_keyboard_return_128_28490 {
            get {
                object obj = ResourceManager.GetObject("ic_keyboard_return_128_28490", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_3_avatar_2754579_120516 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-3-avatar-2754579_120516", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_3_avatar_2754579_1205161 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-3-avatar-2754579_1205161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_check_4341282_120572 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-check-4341282_120572", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_check_4341282_1205721 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-check-4341282_1205721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_home_4341294_120570 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-home-4341294_120570", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_home_4341294_1205701 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-home-4341294_1205701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconfinder_home_4341294_1205702 {
            get {
                object obj = ResourceManager.GetObject("iconfinder-home-4341294_1205702", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keylock_icon_150156 {
            get {
                object obj = ResourceManager.GetObject("keylock_icon_150156", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keylock_icon_1501561 {
            get {
                object obj = ResourceManager.GetObject("keylock_icon_1501561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keylock_icon_1501562 {
            get {
                object obj = ResourceManager.GetObject("keylock_icon_1501562", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightning_bolt_shadow_icon_icons_com_73510 {
            get {
                object obj = ResourceManager.GetObject("lightning-bolt-shadow_icon-icons.com_73510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_symbol_of_three_items_with_dots_icon_icons_com_72994 {
            get {
                object obj = ResourceManager.GetObject("list-symbol-of-three-items-with-dots_icon-icons.com_72994", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap market_research_analytics_chart_analysis_icon_161204 {
            get {
                object obj = ResourceManager.GetObject("market_research_analytics_chart_analysis_icon_161204", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap market_research_analytics_chart_analysis_icon_1612041 {
            get {
                object obj = ResourceManager.GetObject("market_research_analytics_chart_analysis_icon_1612041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap note_task_comment_message_edit_write_108613 {
            get {
                object obj = ResourceManager.GetObject("note-task-comment-message-edit-write_108613", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap note_task_comment_message_edit_write_1086131 {
            get {
                object obj = ResourceManager.GetObject("note-task-comment-message-edit-write_1086131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap organizer_calendar_pen_note_6134 {
            get {
                object obj = ResourceManager.GetObject("organizer_calendar_pen_note_6134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pay_cash_bill_money_buy_icon_143287 {
            get {
                object obj = ResourceManager.GetObject("pay_cash_bill_money_buy_icon_143287", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pay_cash_payment_money_dollar_bill_icon_143267 {
            get {
                object obj = ResourceManager.GetObject("pay_cash_payment_money_dollar_bill_icon_143267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_lying_on_bed_inside_a_home_icon_icons_com_70419 {
            get {
                object obj = ResourceManager.GetObject("person-lying-on-bed-inside-a-home_icon-icons.com_70419", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_lying_on_bed_inside_a_home_icon_icons1 {
            get {
                object obj = ResourceManager.GetObject("person-lying-on-bed-inside-a-home_icon-icons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_lying_on_bed_inside_a_home_icon_icons2 {
            get {
                object obj = ResourceManager.GetObject("person-lying-on-bed-inside-a-home_icon-icons2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_lying_on_bed_inside_a_home_icon_icons3 {
            get {
                object obj = ResourceManager.GetObject("person-lying-on-bed-inside-a-home_icon-icons3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preview_search_find_locate_1551 {
            get {
                object obj = ResourceManager.GetObject("preview_search_find_locate_1551", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_circular_button_1_icon_icons_com_69968 {
            get {
                object obj = ResourceManager.GetObject("question-circular-button-1_icon-icons.com_69968", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_delete_close_1075 {
            get {
                object obj = ResourceManager.GetObject("remove_delete_close_1075", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_37110 {
            get {
                object obj = ResourceManager.GetObject("Save_37110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_371101 {
            get {
                object obj = ResourceManager.GetObject("Save_371101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_find_locate_1542 {
            get {
                object obj = ResourceManager.GetObject("Search_find_locate_1542", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_find_locate_15421 {
            get {
                object obj = ResourceManager.GetObject("Search_find_locate_15421", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_locate_find_6278 {
            get {
                object obj = ResourceManager.GetObject("search_locate_find_6278", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_locate_find_62781 {
            get {
                object obj = ResourceManager.GetObject("search_locate_find_62781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shoppaymentorderbuy_04_icon_icons_com_73886 {
            get {
                object obj = ResourceManager.GetObject("shoppaymentorderbuy-04_icon-icons.com_73886", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shoppaymentorderbuy_23_icon_icons_com_73884 {
            get {
                object obj = ResourceManager.GetObject("shoppaymentorderbuy-23_icon-icons.com_73884", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shoppaymentorderbuy_23_icon_icons1 {
            get {
                object obj = ResourceManager.GetObject("shoppaymentorderbuy-23_icon-icons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap single_bed_icon_150167 {
            get {
                object obj = ResourceManager.GetObject("single_bed_icon_150167", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap single_bed_icon_1501671 {
            get {
                object obj = ResourceManager.GetObject("single_bed_icon_1501671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap systemlogout_94057 {
            get {
                object obj = ResourceManager.GetObject("systemlogout_94057", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap systemlogout_940571 {
            get {
                object obj = ResourceManager.GetObject("systemlogout_940571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap systemlogout_940572 {
            get {
                object obj = ResourceManager.GetObject("systemlogout_940572", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tải_xuống {
            get {
                object obj = ResourceManager.GetObject("tải xuống", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick_yes_approve_accept_green_icon_icons_com_55991 {
            get {
                object obj = ResourceManager.GetObject("tick_yes_approve_accept_green_icon-icons.com_55991", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick_yes_approve_accept_green_icon_icons1 {
            get {
                object obj = ResourceManager.GetObject("tick_yes_approve_accept_green_icon-icons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick_yes_approve_accept_green_icon_icons2 {
            get {
                object obj = ResourceManager.GetObject("tick_yes_approve_accept_green_icon-icons2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vcsremoved_93492 {
            get {
                object obj = ResourceManager.GetObject("vcsremoved_93492", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vcsremoved_934921 {
            get {
                object obj = ResourceManager.GetObject("vcsremoved_934921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vcsremoved_934922 {
            get {
                object obj = ResourceManager.GetObject("vcsremoved_934922", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wondicon_ui_free_logout_111256 {
            get {
                object obj = ResourceManager.GetObject("wondicon-ui-free-logout_111256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wondicon_ui_free_logout_1112561 {
            get {
                object obj = ResourceManager.GetObject("wondicon-ui-free-logout_1112561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wondicon_ui_free_logout_1112562 {
            get {
                object obj = ResourceManager.GetObject("wondicon-ui-free-logout_1112562", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout_zoom_search_find_1530 {
            get {
                object obj = ResourceManager.GetObject("zoomout_zoom_search_find_1530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout_zoom_search_find_15301 {
            get {
                object obj = ResourceManager.GetObject("zoomout_zoom_search_find_15301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout_zoom_search_find_15302 {
            get {
                object obj = ResourceManager.GetObject("zoomout_zoom_search_find_15302", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout_zoom_search_find_15303 {
            get {
                object obj = ResourceManager.GetObject("zoomout_zoom_search_find_15303", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout_zoom_search_find_15304 {
            get {
                object obj = ResourceManager.GetObject("zoomout_zoom_search_find_15304", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
